### ISSUE TITLE
Implement chat room

### ISSUE THREAD

**Issue by kadartamascsaba** [triqla/deep-learning-ubbse2015#51]
REQ#DEF#006, REQ#DEF#003

As a user I want to join in a conference room so that I can talk with other participants.

Implement conference room provider in the backend.

**Comment by ghost** [comment]
Do you really want a chat additionally to the CONFERENCE?

Can you look up the way GOOGLE TALK implements talk?

**Comment by ablenesi** [comment]
We will review this today, because there is no chat functionality.

**Comment by ablenesi** [comment]
Won't do
